server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packages-to-scan: com.quriously.signup

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: 'update'

env:
  secret-key: "taxijjangsecretkey"
